export  const roadmapData = [
    {
        title: "SELF-REFLECTION",
        country: null ,
        disable: false,
        description: "Understanding who you are is the first step of crafting a strong college application. You cannot convey your vivid self through your college application if you don’t have a clear image of who you are.",
        view: false,
        tasks: [
            {
                heading: "MBTI Test",
                estimated_time: '30/6/2024',
                type: 'optional',
                checked: false,
                task_description: "<ul><li>One of the most important elements of a compelling college application is authentic self-reflection. The ability to understand and convey your true identity shapes every aspect of your application.</li><li>This test serves as a starting point for deeper self-exploration. Rather than accepting the results at face value, use them as a catalyst to examine who you are and what you aspire to achieve. These insights will not only strengthen your college applications but also guide your broader life journey.</li></ul>",
            },
            {
                heading: "Interest Profiler",
                estimated_time: '30/6/2024',
                type: 'optional',
                checked: false,
                task_description: "<p>Understanding your career path begins with understanding yourself. The O*NET Interest Profiler is a thoughtfully designed tool that helps illuminate the types of work that would bring you genuine satisfaction and engagement. It measures six fundamental dimensions of work interests:</p><ul><li>Realistic: Your connection to hands-on work with tools, machines, and physical projects</li><li>Investigative: Your drive to analyze, research, and understand complex questions</li><li>Artistic: Your inclination toward creative expression through various mediums</li><li>Social: Your natural orientation toward helping, teaching, and supporting others</li><li>Enterprising: Your capacity for leadership, persuasion, and achieving goals</li><li>Conventional: Your appreciation for organization, detail, and systematic approaches</li></ul><p>The assessment takes 10-30 minutes. Remember, these results aren’t meant to limit you - they’re meant to illuminate possibilities you might not have considered. Use them as a starting point to explore occupations that could align with your natural interests and talents.</p>",
            },
            {
                heading: "Reflect on life experiences",
                estimated_time: '30/6/2024',
                type: 'optional',
                checked: false,
                task_description: "<ul><li>Take a moment to reflect on your past experiences and how they’ve shaped who you are. You can also chat with someone you trust, whether it’s a teacher, friend, or family member.</li><li>Here are a few questions to guide your reflection, though you may find your own path of self-discovery leads to different questions entirely.<ul><li>What experiences keep coming back to your mind?</li><li>When have you felt most proud of your choices?</li><li>Which challenges taught you something unexpected about yourself?</li><li>What activities have always energized you, even as a child?</li><li>When did you surprise yourself by what you could do?</li></ul></li></ul>",
            },
        ],
    },
    {
        title: "PRE-APPLICATION",
        country: null ,
        disable: false,
        description: 'Take a moment to consider how these four key steps - choosing your major, focusing your activities, joining competitions, and exploring internships - create a strategic foundation for your college journey. Together, they build compelling evidence that demonstrates not just your interests, but your real commitment to and experience in your chosen field of study.',
        view: false,
        tasks: [
            {
                heading: "Find your major",
                estimated_time: '30/6/2024',
                type: 'Require',
                checked: false,
                task_description: "<p>Choose a major suitable to you, based on your interests, results of your MBTI test and also your career quiz.</p><p>Finalizing your major early will help you in choosing ECs related to your chosen major that will carry more weight in your college application.</p><p>Based on your interests and MBTI test, here are some suggested majors for you:</p>",
            },
            {
                heading: "Finalize form of EC",
                estimated_time: '30/9/2024',
                type: 'Require',
                checked: false,
                task_description: "<ul><li>Choose your ECs strategically based on your major and your interests. You should finalize your ECs before the summer of Grade 11 to make time to do the actual activity.</li><li>Based on your interests, here are some activities Arrowster suggest that you take-part in. However, always remember: quality is always more important than quantity. Choose a few activities that excites you and participate actively:</li></ul>",
            },
            {
                heading: "Join Major-related Competitions",
                estimated_time: 'As soon as possible',
                type: 'optional',
                checked: false,
                task_description: "<p>Achieving success in competitions can significantly enhance your application. The impact of these accomplishments on your application will be influenced by the following factors:</p><ul><li>Scale of the competition</li><li>Reputation and level of competitiveness</li><li>Relevance to your chosen field of study</li></ul><p>Based on your interests, here are some competitions Arrowster suggest that you take-part in.</p>",
            },
            {
                heading: "Complete Internship",
                estimated_time: '30/9/2024',
                type: 'optional',
                checked: false,
                task_description: "<ul><li>If possible, seek an internship related to your intended major. It shows your passion, commitment, and readiness for future challenges</li><li>Getting a meaningful internship in high school might seem impossible. While your college friends have career fairs and established recruiting paths, you’re left wondering if anyone will take a chance on you. But here’s the truth: real opportunities exist, even if the path isn’t obvious.</li><li>Two Things Matter Most:<ul><li>Who You Know - Your network</li><li>How Bold You Are - Sometimes you need to ignore the “requirements” and just go for it</li></ul></li><li>Start Building Your Network (You Already Have One):<ul><li>Your teachers are your first champions - build genuine relationships with them</li><li>Connect with your friends’ parents who work in interesting fields</li><li>Reach out to former students who’ve landed great internships</li><li>Join online communities where professionals hang out (Stack Overflow, GitHub, relevant forums)</li></ul></li><li>Be Bold:<ul><li>Apply for college internships anyway - my friend landed at NASA this way</li><li>Reach out directly to companies you admire</li><li>Don’t limit yourself to familiar industries</li><li>Keep following up - persistence often matters more than perfection</li></ul></li><li>Remember: Companies aren’t just looking for experience (you’re in high school - they know you don’t have much). They’re looking for curiosity, initiative, and eagerness to learn. Sometimes getting that dream internship is simply about being brave enough to ask and persistent enough to keep asking.</li><li>Your first step? Pick one person in your network - a teacher, a friend’s parent, anyone - and reach out this week. The worst they can say is no.</li><li>Here are some of Arrowster’s suggested job portal that may help you with your search:<ul><li>Topcv.vn - Largest Vietnamese job portal</li><li>Ybox.vn - Youth and internship focused</li><li>Glints.com/vn - Multi-country professional network</li><li>Vietnamworks.com - Premium careers platform</li><li>Jobstreet.vn - Wide range job listings</li><li>123job.vn - New generation job board</li><li>Vn.indeed.com - Global jobs localized</li><li>Vieclam24h.vn - Comprehensive job site</li><li>Mywork.com.vn - All-level positions portal</li><li>Careerbuilder.vn - US-backed recruitment site</li><li>Timviec365.vn - Free posting platform</li><li>Jobsgo.vn - Smart job matching</li><li>Careerlink.vn - Location-based job search</li><li>Topdev.vn - IT specialists platform Itviec.com - Tech recruitment hub</li></ul></li></ul>",
            },
        ],
    },
    {
        title: "ACADEMICS",
        country: null ,
        disable: false,
        description: "",
        view: false,
        tasks: [
            {
                heading: "Take AP Test",
                estimated_time: '31/5/2024',
                type: 'optional',
                checked: false,
                task_description: "<p>AP tests can strengthen your academic story. These subject-specific exams not only demonstrate your readiness for college-level work but also offer a universal way to showcase your abilities, regardless of your high school curriculum.</p><p>Here’s why AP tests are worth considering:</p><ul><li>They validate your mastery in specific subjects that align with your intended major</li><li>They can translate into actual college credits, giving you a head start in your college journey</li><li>You can take them without enrolling in AP classes - particularly valuable if your school doesn’t offer an international curriculum</li><li>They provide external validation of your academic abilities through a standardized measure that colleges trust</li></ul>",
            },
            {
                heading: "Complete Standardized English Test",
                estimated_time: '30/9/2024',
                type: 'Require',
                checked: false,
                task_description: "<p>As International Students, you are required to provide a standardized English proficiency test as part of your college application. While these tests - IELTS, TOEFL, and DET - are important markers, they’re simply meant to show colleges you can thrive in an English-speaking academic environment.</p><p>Remember: These tests aren’t about achieving the highest possible score. Instead, focus on comfortably exceeding your target schools’ minimum requirements. This ensures your English proficiency won’t be a concern, allowing admissions officers to focus on the unique perspectives and experiences you bring.</p>",
            },
            {
                heading: "Complete SAT/ACT",
                estimated_time: '30/9/2024',
                type: 'Require',
                checked: false,
                task_description: "<p>While this item is required for some college and is optional for some, having a standardized test score will also help put your previous training into perspective and help admission officers be more confidence in your success in college.</p>",
            },
            {
                heading: "Maintain high GPA",
                estimated_time: '31/12/2024',
                type: 'Require',
                checked: false,
                task_description: "<ul><li>Your grades at school is one of the key indicators admission committees use to predict your success in college. Generally, the higher your GPA is, the better.</li><li>Colleges often consider your Grade 9 to Grade 12 GPA for admission. Makes sure you maintain a high GPA an an upward overall trajectories in your GPA. Additionally, for your Major, we suggest that you maintain an excellent GPA in these subjects:</li></ul>",
            },
        ],
    },
    {
        title: "APPLICATION MATERIALS",
        country: null ,
        disable: false,
        description: "After much preparation, it's finally time to pull your application materials together and send them to your desired college!",
        view: false,
        tasks: [
            {
                heading: "Fill in personal information",
                estimated_time: "30/6/2024",
                type: 'Require',
                checked: false,
                task_description: "Link to fill in personal information: - Personal information - Academic info - Family background",
            },
            {
                heading: "Choose School list",
                estimated_time: "30/6/2024",
                type: 'Require',
                checked: false,
                task_description: "When applying to college, it's important to create a balanced list of schools that includes reach, target, and safety options. Here are the key steps: - Identify your academic and personal priorities. Consider factors like location, size, cost, majors offered, campus culture, etc. This will help you find good matches. - Talk to your counselor. They can provide personalized recommendations based on your profile and goals. - Attend college fairs and info sessions. These events let you explore options and connect with admissions. - Visit campuses if possible. This gives you a feel for the environment.",
            },
            {
                heading: "Fill in activity list",
                estimated_time: "09/01/2025",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Honor & Rewards",
                estimated_time: "09/01/2025",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Upload Resume/CV",
                estimated_time: "09/01/2025",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Request documents",
                estimated_time: "09/01/2025",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Request Official School Transcript",
                estimated_time: "09/01/2025",
                type: 'Require',
                checked: false,
                task_description: "You can request this from your schools. Transcript for Grade 9, 10, 11, and first semester is required. You will have to amend your Grade 12 first semester transcript when it's available, and provide schools with your full transcript when you matriculate. Unless high schools provide students with English transcripts, you need to provide a notarized translation for your college application. Ask for your transcript at least 2 weeks before the application deadline so that you can receive it in time.",
            },
        ],
    },
    {
        title: "Apply for EU",
        country: "europe",
        disable: false,
        description: "",
        view: false,
        tasks: [
            {
                heading: "Complete Personal Statement",
                estimated_time: "15/12/2024",
                type: 'optional',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit Application",
                estimated_time: "16/12/2024",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit Outside Scholarship Application",
                estimated_time: "16/12/2024",
                type: 'optional',
                checked: false,
                task_description: "",
            },
        ],
    },
    {
        title: "Apply for UK",
        country: "united_kingdom",
        disable: false,
        description: "",
        view: false,
        tasks: [
            {
                heading: "Complete Personal Statement",
                estimated_time: "15/12/2024",
                type: 'optional',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit Application",
                estimated_time: "16/12/2024",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit Outside Scholarship Application",
                estimated_time: "16/12/2024",
                type: 'optional',
                checked: false,
                task_description: "",
            },
        ],
    },
    {
        title: "Apply for Australia",
        country: "australia",
        disable: false,
        description: "",
        view: false,
        tasks: [
            {
                heading: "Complete Personal Statement",
                estimated_time: "13/02/2025",
                type: 'optional',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit Application",
                estimated_time: "14/02/2025",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit Outside Scholarship Application",
                estimated_time: "14/02/2025",
                type: 'optional',
                checked: false,
                task_description: "",
            },
        ],
    },
    {
        title: "Apply for Canada",
        country: "canada",
        disable: false,
        description: "",
        view: false,
        tasks: [
            {
                heading: "Complete Personal Statement",
                estimated_time: "1/10/2024",
                type: 'optional',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit Application",
                estimated_time: "2/10/2024",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit Outside Scholarship Application",
                estimated_time: "2/10/2024",
                type: 'optional',
                checked: false,
                task_description: "",
            },
        ],
    },
    {
        title: "Apply for US",
        country: "united_states",
        disable: false,
        description: "",
        view: false,
        tasks: [
            {
                heading: "Complete Personal Statement",
                estimated_time: "10/10/2024",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Complete Supplemental Essay",
                estimated_time: "17/10/2024",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Complete Common Application",
                estimated_time: "24/10/2024",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit School Report",
                estimated_time: "24/10/2024",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit Counselor Recommnedation",
                estimated_time: "24/10/2024",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit Teacher Evaluation",
                estimated_time: "24/10/2024",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit Early Decision Agreement (if applicable)",
                estimated_time: "24/10/2024",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Fill out CSS Profile/ Scholarship Applications",
                estimated_time: "08/10/2024",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit Application",
                estimated_time: "25/10/2024",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Submit Optional Art/Music Supplements",
                estimated_time: "25/10/2024",
                type: 'optional',
                checked: false,
                task_description: "",
            },
        ],
    },
    {
        title: "POST-APPLICATION ADDITIONAL MATERIALS",
        country: null ,
        disable: false,
        description: "",
        view: false,
        tasks: [
            {
                heading: "Submit Final report and Transcript",
                estimated_time: "15/06/2025",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Pay Deposit & Submit Bank Statement to College",
                estimated_time: "1/5/2025",
                type: 'Require',
                checked: false,
                task_description: "<p>The specifics deposit amount will depends on the University. Typically, the deposit is between $100 and $400, and is non-refundable.</p><p>Ideal Flow:<ul><li>Student get results + make final decision on schools from our portal</li><li>This step informs them how much they need to pay and deadline for deposit</li><li>Allows them to submit deposit proof on our portal directly</li></ul></p>",
            },
            {
                heading: "Receive I-20 from College",
                estimated_time: "15/5/2025",
                type: 'Require',
                checked: false,
                task_description: "",
            },
            {
                heading: "Book Appointment with Embassy",
                estimated_time: "01/06/2025",
                type: 'Require',
                checked: false,
                task_description: "<p>Book you appointment</p><p>The embassy is typically very busy in the summer. Book your appointment early.</p>",
            },
        ],
    },
];